name: flutter_research_gnp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  equatable: ^2.0.5
  logger: ^1.3.0
  intl: ^0.18.0
  auto_route: ^7.1.0
  scroll_to_index: ^3.0.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0
  auto_route_generator: ^7.0.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
